name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/main/kotlin/tsuki/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository 🌏
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # v6.0.2
        with:
          fetch-depth: 0

      - name: Fetch latest commit 🔖
        id: meta
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up Java environment 🔧
        uses: actions/setup-java@b622de1dfa918ecc0ab28f40cd42e3c3752cd6c5 # v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle environment 📦
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          gradle-version: '8.14.3'

      - name: Setup Android SDK 🚀
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1

      - name: Run buildJar task 🚀
        run: chmod +x gradlew && ./gradlew buildJar --rerun-tasks

      - name: Upload to GitHub Release 📤
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          tag_name: ${{ steps.meta.outputs.sha_short }}
          name: "${{ steps.meta.outputs.sha_short }}"
          files: build/libs/vn.jar
          token: ${{ secrets.GITHUB_TOKEN }}
